name: Publish GH - Pages

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Choco Install DocFx
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish OAT.Blazor --no-restore
    - name: Run DocFx
      run: docfx docfx/docfx.json
    - name: Move DocFx Output Into Place
      run: mv docfx/_site/ toPublish/
    - name: Move Blazor Output into Place
      run: mv OAT.Blazor/bin/Debug/netstandard2.1/publish/wwwroot toPublish/Blazor
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: toPublish